//
// Generated file, do not edit! Created by nedtool 5.6 from node/communication/routing/ssCellularRouting/SSCellularRouting.msg.
//

#ifndef __SSCELLULARROUTING_M_H
#define __SSCELLULARROUTING_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "node/communication/routing/RoutingPacket_m.h"
// }}

/**
 * Enum generated from <tt>node/communication/routing/ssCellularRouting/SSCellularRouting.msg:7</tt> by nedtool.
 * <pre>
 * enum SSCellularRoutingPacketType
 * {
 *     HELLO_PACKET = 0;
 *     CL_ANNOUNCEMENT = 1;
 *     CL_CONFIRMATION = 2;
 *     BS_UPDATE_PACKET = 3;
 *     LINK_REQUEST = 4;
 *     LINK_ACK = 5;
 *     LINK_ESTABLISHED = 6;
 *     INTRA_CELL_ROUTING_UPDATE = 7;
 *     CL_COMMAND_PACKET = 8;
 *     NCL_CONFIRM_PACKET = 9;
 *     ROUTING_TREE_UPDATE_PACKET = 10;
 *     CH_ANNOUNCEMENT_PACKET = 11;
 *     DATA_PACKET = 12;
 *     ANNOUNCE_CELL_HOP = 13;
 *     SENSOR_DATA = 14;
 * }
 * </pre>
 */
enum SSCellularRoutingPacketType {
    HELLO_PACKET = 0,
    CL_ANNOUNCEMENT = 1,
    CL_CONFIRMATION = 2,
    BS_UPDATE_PACKET = 3,
    LINK_REQUEST = 4,
    LINK_ACK = 5,
    LINK_ESTABLISHED = 6,
    INTRA_CELL_ROUTING_UPDATE = 7,
    CL_COMMAND_PACKET = 8,
    NCL_CONFIRM_PACKET = 9,
    ROUTING_TREE_UPDATE_PACKET = 10,
    CH_ANNOUNCEMENT_PACKET = 11,
    DATA_PACKET = 12,
    ANNOUNCE_CELL_HOP = 13,
    SENSOR_DATA = 14
};

/**
 * Struct generated from node/communication/routing/ssCellularRouting/SSCellularRouting.msg:25 by nedtool.
 */
struct SSSensorInfo
{
    SSSensorInfo();
    int dataId;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const SSSensorInfo& a);
void __doUnpacking(omnetpp::cCommBuffer *b, SSSensorInfo& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SSSensorInfo& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SSSensorInfo& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>node/communication/routing/ssCellularRouting/SSCellularRouting.msg:29</tt> by nedtool.
 * <pre>
 * packet SSCellularRoutingPacket extends RoutingPacket
 * {
 *     int packetType \@enum(SSCellularRoutingPacketType);
 * 
 *     SSSensorInfo sensorData;
 * }
 * </pre>
 */
class SSCellularRoutingPacket : public ::RoutingPacket
{
  protected:
    int packetType;
    SSSensorInfo sensorData;

  private:
    void copy(const SSCellularRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SSCellularRoutingPacket&);

  public:
    SSCellularRoutingPacket(const char *name=nullptr, short kind=0);
    SSCellularRoutingPacket(const SSCellularRoutingPacket& other);
    virtual ~SSCellularRoutingPacket();
    SSCellularRoutingPacket& operator=(const SSCellularRoutingPacket& other);
    virtual SSCellularRoutingPacket *dup() const override {return new SSCellularRoutingPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPacketType() const;
    virtual void setPacketType(int packetType);
    virtual SSSensorInfo& getSensorData();
    virtual const SSSensorInfo& getSensorData() const {return const_cast<SSCellularRoutingPacket*>(this)->getSensorData();}
    virtual void setSensorData(const SSSensorInfo& sensorData);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SSCellularRoutingPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SSCellularRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SSCELLULARROUTING_M_H

