//
// Generated file, do not edit! Created by nedtool 5.6 from node/communication/mac/tunableMac/TunableMacPacket.msg.
//

#ifndef __TUNABLEMACPACKET_M_H
#define __TUNABLEMACPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "node/communication/mac/MacPacket_m.h"
// }}

/**
 * Enum generated from <tt>node/communication/mac/tunableMac/TunableMacPacket.msg:20</tt> by nedtool.
 * <pre>
 * // Sửa đổi 1: Thêm các loại frame mới và dùng tên enum nhất quán
 * enum TunableMacFrameType
 * {
 *     DATA_FRAME = 0;
 *     BEACON_FRAME = 1;   // Giữ lại để không gây lỗi, dù không còn được sử dụng tích cực
 *     RTS_FRAME = 2;      // Thêm mới
 *     CTS_FRAME = 3;      // Thêm mới
 *     ACK_FRAME = 4;      // Thêm mới
 * } // Sửa đổi 2: Thêm dấu chấm phẩy (;) để kết thúc khai báo enum
 * </pre>
 */
enum TunableMacFrameType {
    DATA_FRAME = 0,
    BEACON_FRAME = 1,
    RTS_FRAME = 2,
    CTS_FRAME = 3,
    ACK_FRAME = 4
};

/**
 * Class generated from <tt>node/communication/mac/tunableMac/TunableMacPacket.msg:28</tt> by nedtool.
 * <pre>
 * packet TunableMacPacket extends MacPacket
 * {
 *     int frameType \@enum(TunableMacFrameType); // Sửa đổi 3: Dùng cú pháp \@enum và thêm dấu chấm phẩy (;)
 * }
 * </pre>
 */
class TunableMacPacket : public ::MacPacket
{
  protected:
    int frameType;

  private:
    void copy(const TunableMacPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TunableMacPacket&);

  public:
    TunableMacPacket(const char *name=nullptr, short kind=0);
    TunableMacPacket(const TunableMacPacket& other);
    virtual ~TunableMacPacket();
    TunableMacPacket& operator=(const TunableMacPacket& other);
    virtual TunableMacPacket *dup() const override {return new TunableMacPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getFrameType() const;
    virtual void setFrameType(int frameType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TunableMacPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TunableMacPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TUNABLEMACPACKET_M_H

